force-app/main/default/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <label>Donation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Donation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Password</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Username</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Project_apex.cls
public class Project_apex {
   public String InputName{get;set;}
   public String InputEmail{get;set;}
   public Integer InputPhoneNumber{get;set;}
   public Integer DonationAmount{get;set;}
   public String regaddress{get;set;}
   public Integer aadhar_number{get;set;}
   public String Username{get;set;}
   public String Password{get;set;}
   public List<Account> recordList{get; set;}
   public Donation__c details{get;set;}
    public Project_apex(){
                //recordList = [select Name from Account where Name like :'Debesh'];
                details=new Donation__c();

    }
public void donationDetails()
{
    insert details;
    details.clear();
}
public void registed_users()
{
  // User__c ur=new User__c(
   //Name=InputName,
   //Address__c=regaddress,
   //Phone__c=InputPhoneNumber,
   //Email_ID__c=InputEmail,
   //Aadhar_number__c=aadhar_number,
   //Username__c=Username,
   //Password__c=Password);
  // insert ur;
    }
    public void acc(){
    }
   
}