force-app/main/default/objects/SMS_Storage__c/SMS_Storage__c.object-meta.xml
<CustomObject>
    <label>SMS Storage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Storage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Status</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Message Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/restApiTextSms.cls
@RestResource(urlMapping='/postsms/*')
global with sharing class restApiTextSms {
    @HttpPost
    global static String postSms(String ANI, String message_Body) {
        //Searching for the contact using the received phone number
        String contactPhone=ANI;
        String textBody=message_Body;
        Contact contRec=new Contact();
        try{
        contRec = [select Id,LastName,MobilePhone from contact where MobilePhone = :contactPhone limit 1];
        }
         catch(Exception ex) {
            System.debug('Error Msg: ' + ex);
            return 'There is no Contact with this number';
        }
        //Creating a record for SMS Storage object
        SMS_Storage__c newSmsInstance = new SMS_Storage__c();	
        //        //Searching for the contact using the received phone number

        if(textBody.length()>0){
            newSmsInstance.Name=contRec.LastName;
            newSmsInstance.Contact__c = contRec.Id;
            newSmsInstance.Message__c = textBody;
            newSmsInstance.Type__c = 'Received';
            newSmsInstance.Message_Type__c='Contact';
        }
        //returning state of the DML operation
        try {
            insert newSmsInstance;
            newSmsInstance.Status__c='Success';
            update newSmsInstance;
                        return 'sucess';

        }
        catch(Exception ex) {
            System.debug('Error Msg: ' + ex);
            return 'Fail';
        }
        
    }
    
}