force-app/main/default/objects/SMS_Storage__c/SMS_Storage__c.object-meta.xml
<CustomObject>
    <label>SMS Storage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Storage__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CaseId</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Message Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/restApiSmsToCase.cls
@RestResource(urlMapping='/smsToCase/*')
global inherited sharing class restApiSmsToCase {
    //Creating record in SMS Storage object with messge type as CASE and returning Wrapper class with newly created case Number and Case Id
    @HttpPost
    global static String postSms(String ANI, String message_Body,String subject,String description) {
        String contactPhone=ANI;
        String textBody=message_Body;
        Contact contRec=new Contact();
        try{
            contRec = [select Id,AccountId,LastName,MobilePhone from contact where MobilePhone = :contactPhone limit 1];
        }
        catch(Exception ex) {
            System.debug('Error Msg: ' + ex);
            return 'There is no contact with this number';
        }
        SMS_Storage__c newSmsInstance = new SMS_Storage__c();   
        textBody=textBody+' '+'('+contactPhone+')';
        
        //Creating new Case after message received
        Case caseObj = new Case(                 
            ContactId = contRec.Id,
            AccountId = contRec.AccountId,
            Subject=subject,
            Description=description,
            Status = 'Working',
            Origin = 'SMS');
        
        insert caseObj;
        caseObj = [select id, casenumber FROM Case where id = : caseObj.id];
  
        
        //Creating a record of the received message
        newSmsInstance.Name=contRec.LastName;
        newSmsInstance.CaseId__c = caseObj.Id;
        newSmsInstance.Contact__c=contRec.Id;
        newSmsInstance.Message__c = textBody;
        newSmsInstance.Type__c = 'Received';
        newSmsInstance.Message_Type__c='Case';
        insert newSmsInstance;
        String str='{"Case Number":"'+caseObj.casenumber+'","Case id":"'+caseObj.Id+'""}';
        return str;
        
    }    
}