force-app/main/default/objects/PhoneNumberList__c/PhoneNumberList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AvailblePhone</label>
</CustomObject>

force-app/main/default/objects/PhoneNumberList__c/fields/FlowId__c.field-meta.xml
<CustomField>
    <fullName>FlowId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FlowId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhoneNumberList__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PhoneNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhoneNumberList__c/fields/Text_Values__c.field-meta.xml
<CustomField>
    <fullName>Text_Values__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Text Values</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/Scheduled_Message__c.object-meta.xml
<CustomObject>
    <label>Scheduled Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduled Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Message__c/fields/Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Action_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Scheduled Messages</relationshipLabel>
    <relationshipName>Scheduled_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Scheduled Messages</relationshipLabel>
    <relationshipName>Scheduled_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Phone_Number_List__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Number List</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Job_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Message__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/SMS_Storage__c.object-meta.xml
<CustomObject>
    <label>SMS Storage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Storage__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Name</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sent Messages</relationshipLabel>
    <relationshipName>CampaignId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Text_Values__c.field-meta.xml
<CustomField>
    <fullName>Text_Values__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Message Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroupMessageScheduler.cls
global with sharing class GroupMessageScheduler implements Schedulable{
    global void execute(SchedulableContext sc){
        Id messageId=null;
        String DNIS,flowid;
        String scheduleId=sc.getTriggerId();
        String Idval=scheduleId.substring(0,15);
        Scheduled_Message__c schedledMessage=[Select Name,Campaign__c,Phone_Number_List__c,Action_Name__c,Contact__c,Contact__r.MobilePhone,Scheduled_Time__c,Scheduled_Message__c from Scheduled_Message__c where Scheduled_Job_Id__c=:Idval];
        System.debug('group schedule'+schedledMessage);
        List<SMS_Storage__c> insertRecord=new List<SMS_Storage__c>();
        list<String>ANI=new List<String>();
        List<PhoneNumberList__c> customSettingValue=PhoneNumberList__c.getall().values();
        for(PhoneNumberList__c record:customSettingValue){
            if(record.Name==schedledMessage.Action_Name__c){
                DNIS='+'+record.PhoneNumber__c;
                flowid=record.FlowId__c;
            }
        }
        CampaignChatBoxApex apicall=new CampaignChatBoxApex();
        Set<Id> setOfMemberIds = new Set<Id>();
        Set<Id> setOfContactIds = new Set<Id>();
        Set<Id> setOfLeadIds = new Set<Id>();
       	List<String> Ids= schedledMessage.Phone_Number_List__c.split(',');
        for(Integer i=0;i<Ids.size();i++){
           setOfMemberIds.add(Ids[i].trim()); 
        }
        System.debug('IdList'+Ids);
        List<CampaignMember> memberList=new List<CampaignMember>();
        memberList=[Select LastName,ContactId,LeadId,Type From CampaignMember Where id In:setOfMemberIds];
        System.debug('memberList'+memberList);
        map<Id,String>memberDetails=new Map<Id,String>();
        for(CampaignMember member :memberList){
            if(member.Type=='Contact')
                setOfContactIds.add(member.ContactId);
            if(member.Type=='Lead')
                setOfLeadIds.add(member.LeadId);
        }
        if(setOfContactIds.size() > 0)
        {
            for(Contact contactInstance:[Select iD,LastName,MobilePhone From Contact where Id IN: setOfContactIds])
            {
                If(contactInstance.MobilePhone!=null){
                    SMS_Storage__c newSmsInstance = new SMS_Storage__c();	
                    newSmsInstance.CampaignId__c=schedledMessage.Campaign__c;
                    newSmsInstance.Text_Values__c=schedledMessage.Action_Name__c;
                    newSmsInstance.Name=contactInstance.LastName;
                    newSmsInstance.Message__c = schedledMessage.Scheduled_Message__c;
                    newSmsInstance.Type__c = 'Sent';
                    newSmsInstance.Message_Type__c='Campaign';
                    newSmsInstance.contact__c=contactInstance.Id;
                    insert newSmsInstance;
                    apicall.callfuture(contactInstance.MobilePhone,schedledMessage.Scheduled_Message__c,DNIS,flowid,newSmsInstance.id); 
                }
            }
        }
        
        if(setOfLeadIds.size()>0)
        {
            for(Lead contactInstance:[Select MobilePhone,LastName From Lead where Id in:setOfLeadIds]){
                system.debug('phone'+contactInstance.MobilePhone);
                If(contactInstance.MobilePhone!=null){
                    SMS_Storage__c newSmsInstance = new SMS_Storage__c();	
                    newSmsInstance.CampaignId__c=schedledMessage.Campaign__c;
                    newSmsInstance.Text_Values__c=schedledMessage.Campaign__c;
                    newSmsInstance.Name=contactInstance.LastName;
                    newSmsInstance.Message__c = schedledMessage.Scheduled_Message__c;
                    newSmsInstance.Type__c = 'Sent';
                    newSmsInstance.Message_Type__c='Campaign';
                    newSmsInstance.lead__c=contactInstance.Id;
                    insert newSmsInstance;
                    apicall.callfuture(contactInstance.MobilePhone,schedledMessage.Scheduled_Message__c,DNIS,flowid,newSmsInstance.id); 
                }
            }
        }
    }
    
}