force-app/main/default/objects/PhoneNumberList__c/PhoneNumberList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AvailblePhone</label>
</CustomObject>

force-app/main/default/objects/PhoneNumberList__c/fields/FlowId__c.field-meta.xml
<CustomField>
    <fullName>FlowId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FlowId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhoneNumberList__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PhoneNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhoneNumberList__c/fields/Text_Values__c.field-meta.xml
<CustomField>
    <fullName>Text_Values__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Text Values</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/Scheduled_Message__c.object-meta.xml
<CustomObject>
    <label>Scheduled Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduled Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Message__c/fields/Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Action_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Scheduled Messages</relationshipLabel>
    <relationshipName>Scheduled_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Scheduled Messages</relationshipLabel>
    <relationshipName>Scheduled_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Phone_Number_List__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Phone Number List</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Job_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Message__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Message__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/SMS_Storage__c.object-meta.xml
<CustomObject>
    <label>SMS Storage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Storage__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Name</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sent Messages</relationshipLabel>
    <relationshipName>CampaignId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Status</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Text_Values__c.field-meta.xml
<CustomField>
    <fullName>Text_Values__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Message Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignChatBoxApex.cls
public inherited sharing class CampaignChatBoxApex {
    //Returning a wrapper class containg Campaign Members and available phone numbers for one to many Message
    @AuraEnabled
    public static wrapperClass CamapignMembers(String CampaignId) {
        wrapperClass returnwrapperClass = new  wrapperClass (); 
        List<CampaignMember> memberList=new List <CampaignMember>();
        returnwrapperClass.memberList=[SELECT CompanyOrAccount,ContactId,Contact.Name,Email,Contact.MobilePhone,Country FROM CampaignMember Where CampaignId=:CampaignId];
        List<PhoneNumberList__c> mcs= new List<PhoneNumberList__c>(); 
        returnwrapperClass.mcs=PhoneNumberList__c.getall().values();
        return returnwrapperClass;
    }
    //Creating the Wrapper class
    public class wrapperClass{
        @AuraEnabled public List<CampaignMember> memberList{get;set;}
        @AuraEnabled public List<PhoneNumberList__c> mcs{get;set;}
    }
    //Creating record in Sms Storage Object and calling the rest Api method with paramaeters.
    @AuraEnabled
    public static void sendSms(List<Id> Ids,String textBody,String campaignId,String textVal){
        List<SMS_Storage__c> insertRecord=new List<SMS_Storage__c>();
        String DNIS;
        String flowid;
        System.debug(Ids);
        list<String>ANI=new List<String>();
        
        List<PhoneNumberList__c> customSettingValue=PhoneNumberList__c.getall().values();
        for(PhoneNumberList__c record:customSettingValue){
            if(record.Name==textVal){
                DNIS='+'+record.PhoneNumber__c;
                flowid=record.FlowId__c;
            }
        }
        Set<Id> setOfMemberIds = new Set<Id>();
        Set<Id> setOfContactIds = new Set<Id>();
        Set<Id> setOfLeadIds = new Set<Id>();
        
        System.debug(textBody);
        setOfMemberIds.addAll(Ids);
        List<CampaignMember> memberList=new List<CampaignMember>();
        memberList=[Select LastName,ContactId,Contact.MobilePhone,LeadId,Lead.mobilePhone,Type From CampaignMember Where id In:setOfMemberIds];
        System.debug('memberList'+memberList);
        map<Id,String>memberDetails=new Map<Id,String>();
        for(CampaignMember member :memberList){
            if(member.Type=='Contact'){
                SMS_Storage__c newSmsInstance = new SMS_Storage__c();	
                newSmsInstance.CampaignId__c=campaignId;
                newSmsInstance.Text_Values__c=textVal;
                newSmsInstance.Name=member.LastName;
                newSmsInstance.Message__c = textBody;
                newSmsInstance.Type__c = 'Sent';
                newSmsInstance.Message_Type__c='Campaign';
                newSmsInstance.contact__c=member.ContactId;
                insert newSmsInstance;
                ChatBoxCallout(member.Contact.MobilePhone,textBody,DNIS,flowid,newSmsInstance.id); 
            }
            if(member.Type=='Lead'){
                SMS_Storage__c newSmsInstance = new SMS_Storage__c();	
                newSmsInstance.CampaignId__c=campaignId;
                newSmsInstance.Text_Values__c=textVal;
                newSmsInstance.Name=member.LastName;
                newSmsInstance.Message__c = textBody;
                newSmsInstance.Type__c = 'Sent';
                newSmsInstance.Message_Type__c='Campaign';
                newSmsInstance.lead__c=member.LeadId;
                insert newSmsInstance;
                ChatBoxCallout(member.Lead.mobilePhone,textBody,DNIS,flowid,newSmsInstance.id); 
                setOfLeadIds.add(member.LeadId);
            }
            
        }
        System.debug('setOfContactIds'+setOfContactIds.size());
        System.debug('setOfLeadIds'+setOfLeadIds);
    }
    //Creating record for schedule Message
    @AuraEnabled
    public static void createScheduleRecord(DateTime datevals,String message,String Action,List<Id>membersList,Id CampaignId){
        Integer Year=datevals.year();
        Integer month=datevals.month();
        Integer datevalue=datevals.day();
        Integer Hour=datevals.hour();
        Integer minute=datevals.minute();
        String scheduleTime='0 '+String.valueOf(minute)+' '+Hour+' '+String.valueOf(datevalue)+' '+month+' ? '+string.valueOf(year);
        System.debug(scheduleTime);
        GroupMessageScheduler scheduleInstance = new GroupMessageScheduler();
        Integer recordAmount=[SELECT COUNT() FROM Scheduled_Message__c WHERE Campaign__C =:CampaignId];
        recordAmount=recordAmount+1;
        String subject='job for '+CampaignId+String.valueOf(recordAmount);
        String jobID = System.schedule(subject,scheduleTime, scheduleInstance);
        String numberList=''; 
        System.debug(membersList);
        for(integer i=0;i<membersList.size();i++){
            if(membersList[i]!=null)
            numberList=numberList+membersList[i]+',';
        }
        
        Scheduled_Message__c messageInstance=new Scheduled_Message__c();
        messageInstance.Name=[Select Name from Campaign where Id=:CampaignId].Name;
        messageInstance.Action_Name__c=Action;
        messageInstance.Campaign__c=CampaignId;
        messageInstance.Scheduled_Time__c=datevals;
        messageInstance.Scheduled_Message__c=message;
        messageInstance.Scheduled_Job_Id__c=jobID;
        messageInstance.Phone_Number_List__c=numberList;
        insert messageInstance;
    }
    public void callfuture(String ANIValue,String message_BodyValue,String DNISValue,String flowIdValue,Id newMessageId){
        ChatBoxCallout(ANIValue,message_BodyValue,DNISValue,flowIdValue,newMessageId);
    }
    //Creating record in salesforce Object(SMS Storage) and calling the rest api function
    @future(callout=true)
    public static void ChatBoxCallout(String ANIValue,String message_BodyValue,String DNISValue,String flowIdValue,Id newMessageId){
        SMS_Storage__c smsInstance=new SMS_Storage__c();
        smsInstance=[Select Status__c from SMS_Storage__c where Id=: newMessageId limit 1];
        try{
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://smart-flows.intelepeer.com/api/apitriggers');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json;charset=UTF-8');
            // Set the body as a JSON object
            request.setBody('{"ANI":"'+ ANIValue +'","message_Body":"'+ message_BodyValue +'","DNIS":"'+ DNISValue+'","flowId":"'+flowIdValue+'","recordId":"'+newMessageId+'"}');
            HttpResponse response = http.send(request);
            System.debug(response.getBody());
            if(response.getStatusCode()==200){
                smsInstance.Status__c='Successfully delivered to smartFlow';
            }
            if(response.getStatusCode()!=200){
                smsInstance.Status__c='Failed to connect to smartFlow';
            }
        }
        catch(Exception e){
            smsInstance.Status__c='Failed to connect to smartFlow';
            System.debug('Message send was un-successful:'+e);        
        }
        update smsInstance;
        
    }
}