force-app/main/default/objects/PhoneNumberList__c/PhoneNumberList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AvailblePhone</label>
</CustomObject>

force-app/main/default/objects/PhoneNumberList__c/fields/FlowId__c.field-meta.xml
<CustomField>
    <fullName>FlowId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FlowId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PhoneNumberList__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PhoneNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminPageApex.cls
public inherited sharing class AdminPageApex {
    @AuraEnabled
    //Returning Available phone number to the script
    public static list<PhoneNumberList__c> numberList(){
        return PhoneNumberList__c.getall().values();
    }
//Creating a new record with respective Phone Number,flowId,text Value received from the Admin in Custom setting  
    @AuraEnabled
    public static list<PhoneNumberList__c> createNewNumber(String Name,String PhoneNumber,Boolean ActiveStatus,String Flow_Id){
        PhoneNumberList__c newRecord=new PhoneNumberList__c();
        newRecord.name=Name;
        newRecord.PhoneNumber__c=PhoneNumber;
        newRecord.Active__C=ActiveStatus;
        newRecord.FlowId__c=Flow_Id;
        insert newRecord;
        return PhoneNumberList__c.getall().values();
    }
    //Updating the Action records and returning the updated Action list and returning the updated Action list
    @AuraEnabled
    public Static list<PhoneNumberList__c> updateRecord(List<PhoneNumberList__c> customlist){
        update customlist;
        return customlist;
    }
    //Deleting Action record
    @AuraEnabled
    public static list<PhoneNumberList__c> deletedRecord(List<PhoneNumberList__c> recordList,String idVal)
    {
                System.debug(recordList);
      PhoneNumberList__c deleteRecord=new PhoneNumberList__c();
        List<PhoneNumberList__c> recordList1=new List<PhoneNumberList__c>();
        for(Integer i=0;i<recordList.size();i++){
            if(idVal==recordList[i].Id){
               deleteRecord= recordList[i];
            }
            else{
                recordList1.add(recordList[i]);
            }
        }
        delete deleteRecord;
        return recordList1;
    }
}