force-app/main/default/objects/Contact/fields/NOC__c.field-meta.xml
<CustomField>
    <fullName>NOC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NOC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Promo__c.field-meta.xml
<CustomField>
    <fullName>Promo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Promo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/requestMessageHistory__c/requestMessageHistory__c.object-meta.xml
<CustomObject>
    <label>requestMessageHistory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Senders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>requestMessageHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/requestMessageHistory__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Action</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/requestMessageHistory__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>requestMessageHistories</relationshipLabel>
    <relationshipName>requestMessageHistories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/requestMessageHistory__c/fields/NotificationList__c.field-meta.xml
<CustomField>
    <fullName>NotificationList__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NotificationList</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/SMS_Storage__c.object-meta.xml
<CustomObject>
    <label>SMS Storage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMS Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Storage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Storage__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SMS Storage</relationshipLabel>
    <relationshipName>SMS_Storage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS_Storage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Message Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/messageAutoResponse.cls
@RestResource(urlMapping='/smsRequest/*')
global inherited sharing class messageAutoResponse {
    @HttpPost
    global static String postSms(String ANI, String action,String NotificationList) {
       String contactDetails=ANI;
        SMS_Storage__c chat = new SMS_Storage__c();	
        chat.Type__c = 'Received';
        chat.Message_Type__c='Contact';
        requestMessageHistory__c newSmsInstance = new requestMessageHistory__c();
        String textBody='';
        Contact contRec=new Contact();
        try
        {
            contRec = [select Id,AccountId,LastName,MobilePhone from contact where MobilePhone = :contactDetails limit 1];
        }
        catch(Exception ex) {
            textBody='cant find any contact with the received phone number';  
        }
         if(NotificationList=='Unknkown'||action=='Unknkown'){	
                            textbody='TBD';
                        }
        if(contRec.Id!=null&&NotificationList!='Unknkown'&&action!='Unknkown'){
            if(action=='subscribe'){
                
                    newSmsInstance.Contact_Name__c=contRec.Id;
                    newSmsInstance.name=contRec.LastName;
                    newSmsInstance.NotificationList__c=NotificationList;
                    chat.Name=contRec.LastName;
                    chat.Contact__c = contRec.Id;
                       
                     
                            if(action=='SUBSCRIBE'){
                                newSmsInstance.Action__c=action; 
                                if(NotificationList=='NOC'){
                                    contRec.NOC__c=true;
                                    textbody='You have Successfully been subscribed to the NOC notification list';
                                    chat.Message__c = 'User subscribed to Notification list: NOC';
                                }
                                if(NotificationList=='Promo'){
                                    contRec.Promo__c=true;
                                    textbody='You have Successfully been subscribed to the Promo notification list';
                                    chat.Message__c = 'User subscribed to Notification list: Promo';
                                }
                                if(NotificationList=='All'){
                                    contRec.NOC__c=true;
                                    contRec.Promo__c=true;	
                                    textbody='You have Successfully been subscribed to the NOC and Promo notification list';
                                    chat.Message__c = 'User subscribed to Notification list: NOC and Promo';
                                }
                            }
            }
                                                    
                            if(action=='UNSUBSCRIBE'.toLowerCase()){
                                      newSmsInstance.Contact_Name__c=contRec.Id;
                    newSmsInstance.name=contRec.LastName;
                    newSmsInstance.NotificationList__c=NotificationList;
                    chat.Name=contRec.LastName;
                    chat.Contact__c = contRec.Id;
                                newSmsInstance.Action__c=action; 
                                if(NotificationList=='NOC'){
                                    contRec.NOC__c=false;
                                    textbody='You have Successfully been UnSubscribed to the NOC notification list';
                                    chat.Message__c = 'User Un-subscribed from Notification list: NOC';
                                }
                                
                                if(NotificationList=='Promo'){
                                    contRec.Promo__c=false;
                                    textbody='You have Successfully been UnSubscribed to the Promo notification list';
                                    chat.Message__c = 'User Un-subscribed from Notification list: Promo';
                                }
                                
                                if(NotificationList=='All'.toLowerCase()){
                                    contRec.NOC__c=false;
                                    contRec.Promo__c=false;	
                                    textbody='You have Successfully UnSubscribed from all notification list';
                                    chat.Message__c = 'User Un-subscribed from Notification list: NOC and Promo';
                                }
                            }
        }
                    try{
                        if(NotificationList!='Unknkown'&&Action!='Unknkown'){
                        insert chat ;
                            System.debug('iserting');
                                                    update contRec;
                        }
                                                                        insert newSmsInstance;

                    }
                    catch(Exception ex) {
                        System.debug('Error Msg: ' + ex);
                        textBody= 'Wrong Input';
                    }
        
        return textBody;
    }
}